tuukul/src/main/java/com/mexicho/view/UserBean.java
package com.mexicho.view;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import com.mexicho.model.Usuario;
import com.mexicho.model.UtilityDB;


import org.primefaces.model.ByteArrayContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author mexicho
 */
@RequestScoped
@ManagedBean
public class UserBean {

    private FacesContext context;

    public UserBean() {
        context = FacesContext.getCurrentInstance();
    }

    public boolean isLogged() {
        return getUsuario() != null;
    }

    public Usuario getUsuario() {
        return (Usuario) context.getExternalContext().getSessionMap().get("usuario");
    }

    public StreamedContent getFotografia() {
        Usuario u = getUsuario();
        if (u.getFotografia() != null) {
            return new ByteArrayContent(u.getFotografia());
        }
        return null;
    }

}

tuukul/src/main/webapp/WEB-INF/facelets/templates/content.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui">

  <main role="main">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhdQCqsXvF4UYs_I4lYbPEzWSsqujPSMg" ></script>
    <ui:insert name ="content">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <br/>
      <br/>
      <br/>
      <br/>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"></h1>
          <p:gmap id="gmap" center="23.382390, -102.291477" zoom="7" type="roadmap" style="width:100%;height:700px" onPointClick="handlePointClick(event);" widgetVar="map"/>
        </div >
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2>Tema 1</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
          <div class="col-md-4">
            <h2>Tema 2</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
          <div class="col-md-4">
            <h2>Tema 3</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
        </div>
        <hr/>
      </div>


    </ui:insert>
  </main>

</ui:composition>

tuukul/src/main/webapp/WEB-INF/facelets/templates/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

  <div class="footer">
    <p>&#169; Ingeniería de Software - 2019 - Mexicho</p>
  </div>

</ui:composition>

tuukul/src/main/webapp/WEB-INF/facelets/templates/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:c="http://xmlns.jcp.org/jsp/jstl/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:p="http://primefaces.org/ui" xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color: #D9DFDF;;">
    <c:choose>
      <c:when test="#{userBean.isLogged() == true}">
        <a class="navbar-brand" href="index.xhtml">
          Mexicho
        </a>
      </c:when>
      <c:otherwise>
        <a class="navbar-brand" href="index.xhtml">
          Mexicho
        </a>
      </c:otherwise>
    </c:choose>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" />
    </button>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav ml-auto">
        <c:choose>
          <c:when test="#{userBean.isLogged() == true}">
            <div class="my-2 my-lg-0">
              <p:graphicImage value="#{userBean.fotografia}" width="48" height="48" />
              <button class="btn btn-primary" style="height:48px;">
                <i class="fa fa-sign-in" aria-hidden="true" />
                #{userBean.usuario.nombre}
              </button>
            </div>
            <div class="my-2 my-lg-0">
              <h:form id="exit">
                <h:commandButton action="#{loginController.logout()}" value="Cerrar Sesión"
                  class="btn btn-outline-success my-2 my-sm-0" style="height:48px;" />
              </h:form>
            </div>
          </c:when>
          <c:otherwise>
            <h:form id="myForm" class="form-inline my-2 my-lg-0">
              <h:inputText value="#{loginController.usuario}" required="true" id="Username" size="15"
                class="form-control mr-sm-2" a:placeholder="Correo Electrónico" />

              <h:inputSecret value="#{loginController.contraseña}" required="true" id="Password"
                class="form-control mr-sm-2" a:placeholder="Contraseña" />

              <h:commandButton action="#{loginController.login}" value="Inicia Sesión"
                class="btn btn-outline-success my-2 my-sm-0" />

            </h:form>
          </c:otherwise>
        </c:choose>
      </div>
    </div>

  </nav>
</ui:composition>

tuukul/src/main/webapp/WEB-INF/facelets/templates/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>

    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Mexicho</title>

    <h:outputStylesheet library="webjars" name="bootstrap/4.0.0-2/css/bootstrap.min-jsf.css" />

</h:head>
<h:body>

    <ui:include src="./header.xhtml" />
    <div class="container">
        <ui:include src="./content.xhtml" />
        <ui:include src="./footer.xhtml" />
    </div>

    <!-- Los dejamos hasta abajo para que cargue la página más rápido-->
    <h:outputScript library="webjars" name="jquery/3.3.1-1/jquery.min.js"/>
    <h:outputScript library="webjars" name="bootstrap/4.0.0-2/js/bootstrap.min.js" />
    <h:outputScript library="webjars" name="https://maps.google.com/maps/api/js?sensor=true" />
    

</h:body>
</html>